language: python
python: "3.7"

matrix:
    include:
        - os: linux
          dist: bionic
          compiler: gcc
          env:
            - CMAKE_COMPILER=g++
            - CONAN_COMPILER=gcc
            - CONAN_COMPILER_VERSION=7
            - CONAN_LIBCXX=libstdc++

        - os: linux
          dist: bionic
          compiler: clang
          env:
            - CMAKE_COMPILER=clang++
            - CONAN_COMPILER=clang
            - CONAN_COMPILER_VERSION=7.0
            - CONAN_LIBCXX=libc++

install:
    # Install conan
    - pip install conan
    # Automatic detection of your arch, compiler, etc.
    - conan user

script:
    - mkdir build
    - cd build
    # Download dependencies and build project
    - conan install .. -s build_type=Debug -s compiler=${CONAN_COMPILER} -s compiler.libcxx=${CONAN_LIBCXX} -s compiler.version=${CONAN_COMPILER_VERSION}
    # Call your build system
    - cmake -DCMAKE_CXX_COMPILER=${CMAKE_COMPILER} ..
    - cmake --build . --config Debug -j`nproc`
