version: '1.0.{build}'

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug

install:
    - cmmd: echo "Downloading conan..."
    - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmmd: pip.exe install conan
    - cmmd: conan user # Create the conan data directory
    - cmmd: conan --version

build_script:
    - cmmd: mkdir build
    - cmmd: conan install . -s build_type=Debug
    - cmmd: cd build
    - cmmd: cmake -G "Visual Studio 16 2019" -A x64 ..
    - cmmd: cmake --build . --config Debug
