version: '1.0.{build}'

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug

install:
    - cmd: echo "Downloading conan..."
    - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmd: pip.exe install conan
    - cmd: conan user # Create the conan data directory
    - cmd: conan --version

build_script:
    - cmd: mkdir build
    - cmd: conan install . -s build_type=Debug
    - cmd: cd build
    - cmd: cmake -G "Visual Studio 16 2019" -A x64 ..
    - cmd: cmake --build . --config Debug
